#!/bin/bash

# 1- after creating folder ~/autonomous/services/automount_USB/

# 2- save this file as ~/autonomous/services/automount_USB/cpmount

# 3- while in directory /usr/local/bin/, create a symlink thusly: 
#	sudo ln -s ~/autonomous/services/automount_USB/cpmount

if mountpoint -q /media/usb1
then
   if mountpoint -q /media/usb2
   then
      if mountpoint -q /media/usb3
      then
         if mointpoint -1 /media/usb4
         then
             echo "No mountpoints available!"
             #You can add more if you need
         else
             /usr/bin/pmount --umask 00 -noatime -r --sync $1 usb4
         fi
      else
         /usr/bin/pmount --umask 000 --noatime -r --sync $1 usb3
      fi
   else
      /usr/bin/pmount --umask 000 --noatime -r --sync $1 usb2
   fi
else
   /usr/bin/pmount --umask 000 --noatime -r --sync $1 usb1
fi